---
- name: Install chrony
  apt:
    name: chrony
    state: present
    update_cache: yes
  become: yes

- name: get the management IP range
  become: true
  shell: "ip route | grep {{ network_interface }} | grep -v default | grep kernel | awk {'print $1'}"
  register: ip_range

- name: Set the management IP range
  set_fact:
    management_ip_range: "{{ ip_range.stdout }}"

- name: copy the chrony.conf file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
  become: true
  notify: Restart chrony service

- name: Ensure chrony service is enabled and started
  systemd:
    name: chrony
    enabled: yes
    state: started
  become: yes

- name: Ensure ntp is not installed (if applicable)
  apt:
    name: ntp
    state: absent
  when: ansible_facts.packages.ntp is defined  # Check if ntp is installed
  become: yes

- name: Disable and mask ntp service (if exists)
  systemd:
    name: ntp
    enabled: no
    masked: yes
    state: stopped
  when: ansible_facts.packages.ntp is defined  # Check if ntp is installed
  become: yes

- name: Disable and mask systemd-timesyncd.service
  systemd:
    name: systemd-timesyncd.service
    enabled: no
    masked: yes
    state: stopped
  become: yes

