---
- name: Install chrony
  apt:
    name: chrony
    state: present
    update_cache: yes
  become: yes

- name: Remove existing server lines from chrony.conf
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: '^server '
    state: absent
  become: yes

- name: Add specific server entries to chrony.conf
  blockinfile:
    path: /etc/chrony/chrony.conf
    block: |
      server 172.17.255.20 iburst
      server 172.17.255.21 iburst
    insertafter: '^#.*Server entries'
  become: yes

- name: Ensure chrony service is enabled and started
  systemd:
    name: chrony
    enabled: yes
    state: started
  become: yes

- name: Ensure ntp is not installed (if applicable)
  apt:
    name: ntp
    state: absent
  when: ansible_facts.packages.ntp is defined  # Check if ntp is installed
  become: yes

- name: Disable and mask ntp service (if exists)
  systemd:
    name: ntp
    enabled: no
    masked: yes
    state: stopped
  when: ansible_facts.packages.ntp is defined  # Check if ntp is installed
  become: yes

- name: Disable and mask systemd-timesyncd.service
  systemd:
    name: systemd-timesyncd.service
    enabled: no
    masked: yes
    state: stopped
  become: yes

