---
- name: Install chrony
  apt:
    name: chrony
    state: present
    update_cache: yes
  become: yes

- name: Remove all lines starting with 'server'
  shell: sed -i '/^pool /d' /etc/chrony/chrony.conf
  become: yes

- name: Remove all lines starting with 'server'
  shell: sed -i '/^server /d' /etc/chrony/chrony.conf
  become: yes

- name: Add specific server entries to chrony.conf
  blockinfile:
    path: /etc/chrony/chrony.conf
    block: |
      {% for ip in chrony_timeserver_ips %}
      server {{ ip }} iburst
      {% endfor %}
    insertafter: '^#.*Server entries'
  with_items: "{{ chrony_timeserver_ips }}"
  notify: Restart chrony service
  become: yes

- name: Ensure chrony service is enabled and started
  systemd:
    name: chrony
    enabled: yes
    state: started
  become: yes

- name: Ensure ntp is not installed (if applicable)
  apt:
    name: ntp
    state: absent
  when: ansible_facts.packages.ntp is defined  # Check if ntp is installed
  become: yes

- name: Disable and mask ntp service (if exists)
  systemd:
    name: ntp
    enabled: no
    masked: yes
    state: stopped
  when: ansible_facts.packages.ntp is defined  # Check if ntp is installed
  become: yes

- name: Disable and mask systemd-timesyncd.service
  systemd:
    name: systemd-timesyncd.service
    enabled: no
    masked: yes
    state: stopped
  become: yes

