---
- include_tasks: filesystem.yml

- include_tasks: system-maintenance.yml

- include_tasks: services.yml

- include_tasks: chrony.yml

- include_tasks: user-accounts.yml

- include_tasks: logging.yml

