---
- include_tasks: scripts.yml
  loop: "{{ security_filesystem_scripts }}"
  loop_control:
    loop_var: script

- name: Check if autofs is installed
  apt:
    name: autofs
    state: absent
    purge: yes
  register: autofs_purge

- name: Stop the autofs service if running
  service:
    name: autofs
    state: stopped
  ignore_errors: true
  when: autofs_purge.changed == false

- name: Mask the autofs service
  systemd:
    name: autofs
    masked: yes

