---
- name: Copy the log permission script to the remote hosts
  ansible.builtin.copy:
    src: files/log-permission.sh
    dest: /usr/local/bin/log-permission.sh
  become: yes

- name: Ensure the script is executable
  file:
    path: /usr/local/bin/log-permission.sh
    mode: '0755'

- name: Run the log-permission.sh script to ensure all logfiles have appropriate access configured
  shell: /usr/local/bin/log-permission.sh
  register: log_permission_output

- name: Display the log-permission.sh output
  debug:
    var: log_permission_output.stdout

- name: Ensure journald service is enabled
  ansible.builtin.systemd:
    name: systemd-journald
    state: started
    enabled: yes

- name: Ensure journald is configured to compress large log files
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^Compress'
    line: 'Compress=yes'
    state: present
  notify: Restart systemd-journald service

- name: Ensure journald is configured to write logfiles to persistent disk
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^Storage'
    line: 'Storage=persistent'
    state: present
  notify: Restart systemd-journald service

- name: Ensure journald is not configured to send logs to rsyslog
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^ForwardToSyslog'
    line: 'ForwardToSyslog=yes'
    state: absent
  notify: Restart systemd-journald service

- name: Ensure accounts in /etc/passwd use shadowed passwords
  ansible.builtin.command:
    cmd: sed -e 's/^\([a-zA-Z0-9_]*\):[^:]*:/\1:x:/' -i /etc/passwd
  become: true

