---
- include_tasks: scripts.yml
  loop: "{{ security_logging_scripts }}"
  loop_control:
    loop_var: script

- name: Install rsyslog
  apt:
    name: rsyslog
    state: present
    update_cache: yes
  become: yes

- name: Ensure rsyslog service is enabled
  ansible.builtin.systemd:
    name: rsyslog
    state: started
    enabled: yes

- name: Ensure rsyslog default file permissions are configured
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^$FileCreateMode'
    line: '$FileCreateMode 0640'
    state: present
  notify: Restart rsyslog service

- name: Ensure journald service is enabled
  ansible.builtin.systemd:
    name: systemd-journald
    state: started
    enabled: yes

- name: Ensure journald is configured to compress large log files
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^Compress'
    line: 'Compress=yes'
    state: present
  notify: Restart systemd-journald service

- name: Ensure journald is configured to write logfiles to persistent disk
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^Storage'
    line: 'Storage=persistent'
    state: present
  notify: Restart systemd-journald service

- name: Ensure journald is configured to send logs to rsyslog
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^ForwardToSyslog'
    line: 'ForwardToSyslog=yes'
    state: absent
  notify: Restart systemd-journald service

- name: Ensure accounts in /etc/passwd use shadowed passwords
  ansible.builtin.command:
    cmd: sed -e 's/^\([a-zA-Z0-9_]*\):[^:]*:/\1:x:/' -i /etc/passwd
  become: true

