---
- name: Check if partitions are mounted
  ansible.builtin.shell: "mount | grep {{ partition }}"
  register: mount_status
  failed_when: mount_status.rc not in [0, 1]  # Ignore 'grep' not finding the line
  changed_when: false

- name: Ensure rw,nosuid,nodev,relatime options are set for partitions in {{ partition }}
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^(.*\s+{{ partition }}\s+\S+\s+defaults)(.*)$'
    line: '\1,rw,nosuid,nodev,relatime 0 0'
    backrefs: yes
  when: mount_status.rc == 0
  register: fstab_status
  become: yes

- name: Remounting the {{ partition }}
  ansible.builtin.shell:
    cmd: mount -o remount {{ partition }}
      #notify: Remount home partition
  when: fstab_status.changed and mount_status.rc == 0 

