---
- name: Ensure sudo is installed
  apt:
    name: sudo
    state: present
  become: yes

- name: apply sudoers settings
  lineinfile:
    path: /etc/sudoers
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items: "{{ privilege_settings }}"
