---
- name: "Copy the {{ script }} script to the remote hosts"
  ansible.builtin.copy:
    src: "{{ script }}"
    dest: "{{ security_script_base_path }}/{{ script }}"
  become: yes

- name: "Ensure the {{ script }} script is executable"
  file:
    path: "{{ security_script_base_path }}/{{ script }}"
    mode: '0755'

- name: "Run the {{ script }} script"
  shell: "{{ security_script_base_path }}/{{ script }}"
  register: script_output

- name: "Display the {{ script }} output"
  debug:
    var: script_output.stdout

