---
- include_tasks: scripts.yml
  loop: "{{ security_ssh_scripts }}"
  loop_control:
    loop_var: script

- name: apply SSH configurations
  lineinfile:
    path: "{{ security_ssh_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items: "{{ ssh_settings }}"
  notify: Restart sshd service
