---
# handlers file for sec-ansible
- name: Reload systemd daemon
  command: systemctl daemon-reload
  become: yes

- name: Restart sshd service
  command: systemctl restart sshd
  become: yes

- name: Restart systemd-journald service
  command: systemctl restart systemd-journald
  become: yes

- name: Restart chrony service
  shell: "systemctl restart chronyd.service && systemctl restart chrony.service"
  become: yes

- name: Restart rsyslog service
  command: systemctl restart rsyslog
  become: yes
